name: Release

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: read
        steps:
            - uses: actions/checkout@v2

            - name: Substitute version in manifest
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'system.json'
              env:
                  version: ${GITHUB_REF_NAME#v}
                  manifest: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.json
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/candelafvtt-${GITHUB_REF_NAME}.zip

            - name: Install dependencies and build
              run: |
                  npm install -g yarn
                  yarn install
                  sh build.sh ${GITHUB_REF_NAME#v}

            - name: Update release with files
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  name: ${{ github.event.release.name }}
                  draft: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: './system.json, ./dist/candelafvtt-${GITHUB_REF_NAME}.zip'
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}
